# Generated by Django 4.2.3 on 2023-11-18 20:06

from django.db import migrations, models
import django.db.models.deletion
import mixins.path_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
                ('answered', models.BooleanField(blank=True, default=False, verbose_name='Отвечено?')),
            ],
            options={
                'verbose_name': 'Заявление',
                'verbose_name_plural': 'Заявления',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название направление')),
                ('main_image', models.ImageField(upload_to='direction/images/%Y-%m-%d', verbose_name='Главное изображение')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Контент')),
                ('icon', models.ImageField(blank=True, default=None, null=True, upload_to='direction/icons', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Направление отряда',
                'verbose_name_plural': 'Направления отрядов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='ФИО человека')),
                ('image', models.ImageField(upload_to='squads/important_people/%Y-%m-%d', verbose_name='Изображение')),
                ('on_main', models.BooleanField(blank=True, default=False, verbose_name='На главную?')),
                ('phone', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Личный телефон')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Личная почта')),
            ],
            options={
                'verbose_name': 'Ключевая фигура',
                'verbose_name_plural': 'Ключевые фигуры',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(max_length=100, unique=True, verbose_name='Позиция персонажа')),
            ],
            options={
                'verbose_name': 'Должность человека',
                'verbose_name_plural': 'Должности людей',
            },
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название отряда')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=mixins.path_mixins.make_dir_for_squad_main_image, verbose_name='Основная фотография')),
                ('description', models.TextField(verbose_name='Описание')),
                ('content', models.TextField(verbose_name='Контент')),
                ('phone', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Телефон отряда')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Почта отряда')),
                ('vk', models.URLField(blank=True, default=None, null=True, verbose_name='Группа "ВКонтакте"')),
                ('telegram', models.URLField(blank=True, default=None, null=True, verbose_name='Группа "Телеграм"')),
                ('create', models.DateField(verbose_name='Дата создания')),
                ('albums', models.ManyToManyField(blank=True, default=None, related_name='squad_albums', to='album.album', verbose_name='Альбомы')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squad', to='squad.direction', verbose_name='Направление отряда')),
                ('figures', models.ManyToManyField(blank=True, default=None, related_name='squad_important_people', to='squad.figure', verbose_name='Ключевые фигуры')),
            ],
            options={
                'verbose_name': 'Отряд',
                'verbose_name_plural': 'Отряды',
                'ordering': ['direction__name'],
            },
        ),
        migrations.AddField(
            model_name='figure',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figures', to='squad.position', verbose_name='Должность'),
        ),
    ]
