# Generated by Django 4.2.3 on 2023-11-18 20:06

from django.db import migrations, models
import django.db.models.deletion
import mixins.path_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название альбома')),
                ('banner', models.ImageField(blank=True, default=None, null=True, upload_to=mixins.path_mixins.make_dir_for_album, verbose_name='Главное изображение альбома')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to=mixins.path_mixins.make_dir_for_album_images, verbose_name='Изображение')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Изображение альбома',
                'verbose_name_plural': 'Изображения альбомов',
                'ordering': ('album',),
            },
        ),
        migrations.AddField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, related_name='album_images', to='album.albumimage', verbose_name='Изображения'),
        ),
    ]
